services:
  postgres:
    container_name: social_notes_postgres
    image: postgres
    environment:
      POSTGRES_USER: "psqluser"
      POSTGRES_PASSWORD: "psqlpasswd"
      POSTGRES_DB: social_notes
      PGDATA: /data/postgres
    volumes:
       - /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  neo4j:
    container_name: social_neo4j
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/NEOPASSFORIINRANGE10
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    volumes:
      - ./neo4j_db/data:/data
      - ./neo4j_db/logs:/logs
      - ./neo4j_db/import:/var/lib/neo4j/import
      - ./neo4j_db/plugins:/plugins