services:
  postgres:
    container_name: social_notes_postgres
    image: postgres
    environment:
      POSTGRES_USER: "psqluser"
      POSTGRES_PASSWORD: "psqlpasswd"
      POSTGRES_DB: social_notes
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres: