port: 4040
auth_client:
  port: localhost:4041
  timeout: 1s
  retries: 1
note_client:
  port: localhost:4042
  timeout: 1s
  retries: 1
friends_client:
  port: localhost:4043
  timeout: 1s
  retries: 1